### ISSUE TITLE
Curated QTL data download

### ISSUE THREAD

**Issue by gonzalobenegas** [calico/borzoi#10]
Hello, thanks for your inspiring paper!

Is there any way to download the curated QTL benchmarking data without paying? I was imagining the files wouldn't be too large to host on a free service.

**Comment by celalp** [comment]
I'm actually having a hard time even with the paid option. I cannot see the data or download it.

**Comment by adamyhe** [comment]
This is like half a year late, but I just posted the QTLs to a public repo:

https://github.com/adamyhe/borzoi_qtls/

If you've got an academic affiliation, I think Google will give you enough intro credits to download the entire 2TB dataset (at least, it did for me).

**Comment by gonzalobenegas** [comment]
Awesome, thank you very much!
