### ISSUE TITLE
final conv block

### ISSUE THREAD

**Issue by samuel-g-bates** [calico/borzoi#12]
Can you please explain the reasoning for having 1920 filter in the final conv block? Enformer uses 2*final channel# of the tower but that doesnt seem to be the case for Borzoi. Just curious as to the purpose.

Thanks,
Sam

**Comment by davek44** [comment]
Hi Sam, I tuned the model size to balance GPU memory and speed. We shrank the model in some ways, relative to Enformer, to achieve other goals like longer sequences and finer prediction resolution. The filter numbers are pretty arbitrary, and values 50% smaller or greater would probably produce similar quality models.
