### ISSUE TITLE
Weights of the mouse head

### ISSUE THREAD

**Issue by gokceneraslan** [calico/borzoi#14]
Paper is amazing Johannes & Dave et al., congrats! I was wondering if the weights of the mouse head are available too.

**Comment by smitkadvani** [comment]
weights for mouse heads are available at 
https://storage.googleapis.com/seqnn-share/borzoi/f0/model1_best.h5
https://storage.googleapis.com/seqnn-share/borzoi/f1/model1_best.h5

https://storage.googleapis.com/seqnn-share/borzoi/f2/model1_best.h5

https://storage.googleapis.com/seqnn-share/borzoi/f3/model1_best.h5
looking at baskerville repository, I realized that they have been following the convention 
0 -> human (model0_best.h5)
1 -> mouse(model1_best.h5)

**Comment by gokceneraslan** [comment]
Oh this is amazing really, thanks so much!

**Comment by davek44** [comment]
Correct
