### ISSUE TITLE
Size of the final cropping layer

### ISSUE THREAD

**Issue by avantikalal** [calico/borzoi#15]
Hi,

based on the parameters file, it seems that the number of positions cropped on either end of the output in Borzoi is 16 (https://github.com/calico/borzoi/blob/main/examples/params_pred.json#L69). However, according to the preprint:

```
In order to avoid less accurate predictions on the sequence boundaries (due to asymmetric visibility), we cropped from each side to focus the loss computation on the center 196, 608 bp.
```

Based on my calculations, this implies that the number of bases cropped on either end should be ((524288-196608)/32)/2 = 5120. Could you clarify the reason for choosing 16? Thanks!

**Comment by davek44** [comment]
Hi Avantika, sorry I wasn't getting notifications on these issues, so you've probably moved on. After model training, you can set the cropping to whatever you want. I.e. the model is still capable of making predictions outside of the training region, so sometimes we reduce the cropping to allow them. That's what's happening in that params file. However, we sometimes see the flank predictions behaving weirdly, and they don't seem to boost the downstream task metrics (like eQTL prediction) at all. Next time, we're likely to handle this aspect differently.
