### ISSUE TITLE
Tissue specificity of model predictions

### ISSUE THREAD

**Issue by fojackson8** [calico/borzoi#16]
Hi, great paper.

I'm just wondering about the tissue specificity of the gene expression predictions. Specifically, if we take model predictions for one tissue, eg monocyte - how do expression predictions for monocyte correlate with true gene exp. values for monocyte versus true gene exp. values for all other tissues? In other words, how specific are gene expression predictions for each particular tissue? 

Apologies if I've missed this in one of the figures somewhere

**Comment by davek44** [comment]
We'll have new versions of these analyses in the final publication coming soon. Generally, the PearsonR for predictions versus observations after we normalize across samples and subtract the mean remains high ~0.7 median.
