### ISSUE TITLE
Fine tuning?

### ISSUE THREAD

**Issue by kawairine** [calico/borzoi#24]
Hi,

Thank you for the amazing model! 

I was wondering if there is any guidance for how to fine-tuning the model? I would like to finetune the model with my human data in both atac- and rna- sequencing.  and if you have any advices if I have control vs disease data - shall I fine tuning on control and disease separately? 

Thank you!

**Comment by JasonTan-code** [comment]
Any updates on fine-tuning code?

**Comment by davek44** [comment]
We'll submit a methods description to bioRxiv and release code for this shortly. The pull request is here https://github.com/calico/baskerville/pull/40, but we're still cleaning and testing.
