### ISSUE TITLE
Baskerville requires TensorFlow 2.15, but Borzoi requires TensorFlow 2.12. How should I install them?

### ISSUE THREAD

**Issue by liameihao** [calico/borzoi#25]
![image](https://github.com/user-attachments/assets/f085e95f-8914-4e8c-9245-d3d8c7233b65)
![image](https://github.com/user-attachments/assets/a4adbf1c-9fa0-4638-a3f4-8c561214b99c)

**Comment by davek44** [comment]
Hi, we updated to tensorflow 2.15. I believe everything from 2.12-2.15 will work fine.
