### ISSUE TITLE
Mini Models unavailable

### ISSUE THREAD

**Issue by saninta0212** [calico/borzoi#27]
I am trying to access the pretrained mini models from the link: https://storage.googleapis.com/seqnn-share/borzoi/mini/. However, when I try to access the link I get a blank web page. How can I get the pre-trained models on different folds? 

If I am not wrong, all 4 of these models are replicates trained on the "SAME DATA" - 
<img width="899" alt="image" src="https://github.com/user-attachments/assets/46df1219-0793-4318-b3a8-952899af0a5d">

**Comment by johli** [comment]
Hi, you have to navigate to the bucket either via the GCP web console (https://console.cloud.google.com/) or via the gsutil command-line:

```
> gsutil ls gs://seqnn-share/borzoi/mini/
gs://seqnn-share/borzoi/mini/
gs://seqnn-share/borzoi/mini/human_all/
gs://seqnn-share/borzoi/mini/human_dnase_atac_rna/
gs://seqnn-share/borzoi/mini/human_gtex/
gs://seqnn-share/borzoi/mini/k562_all/
gs://seqnn-share/borzoi/mini/k562_dnase_atac_rna/
gs://seqnn-share/borzoi/mini/k562_rna/
gs://seqnn-share/borzoi/mini/multispecies_all/
gs://seqnn-share/borzoi/mini/multispecies_dnase_atac_rna/
gs://seqnn-share/borzoi/mini/multispecies_no_unet/
gs://seqnn-share/borzoi/mini/multispecies_rna/
```

The large model ensemble was trained with identical replicates, but the mini models were trained as cross-validation folds.

Best,

Johannes
