### ISSUE TITLE
Questions about the inptus of borzoi prediction

### ISSUE THREAD

**Issue by HelloWorldLTY** [calico/borzoi#29]
Hi, thanks for your great work. I wonder if ther input seq lengh of borzoi (524288) is a very strict requirement, as I found that many genes do not have such window size in their chrom (like 200 out of 18000 candidates). Is it possible to adjust its window size for fine-tuning model? Thanks a lot.

**Comment by davek44** [comment]
Hi, this isn't strict, but the self-attention relative position encodings are set based on the sequence length. It would be safer to just pad with N's on each side. We have a transfer learning pipeline on the way that will make it easier to adjust the sequence length, and maintain the original self-attention sequence length. https://github.com/calico/baskerville/blob/transfer/docs/transfer/transfer.md

**Comment by grpinto** [comment]
But doesn't borzoi expect 4 channels ? How would we padd it with Ns ?
