### ISSUE TITLE
Downloading training data

### ISSUE THREAD

**Issue by ekinda** [calico/borzoi#31]
Hello, thank you for all the documentation and tutorials! My question is about downloading the training data.

1. Is the data in GCP in bigwig format, or already processed to .w5 with the provided scripts?
2. For downloading from GCP, I calculated the approximate cost at around 500$ (assuming 4-5 TB, download from EU), does that sound like a reasonable estimate?
3. For downloading directly from ENCODE, FANTOM etc., do you have a list of direct download links? That would be extremely helpful.

Best
Ekin

**Comment by davek44** [comment]
1. The data is TFRecords.
2. It's 2.3 TB. The bucket is set to "standard". According to this guide, the download should actually be free: https://cloud.google.com/storage/pricing
3. I do not have direct download links, but they should be straightforward to determine from the targets table with the sample identifiers.

**Comment by ekinda** [comment]
Thank you for the response. I created my own list for the direct ENCODE links in the meantime.

In case other people have similar questions, this link lets you view the data structure: https://console.cloud.google.com/storage/browser/borzoi-paper

**Comment by yangzhao1230** [comment]
Thank you for the information shared here. I'm confused about whether downloading the data requires payment or not. The README documentation mentions that the data is stored in a "Requester Pays" bucket (requiring users to pay), while in this issue @davek44  states that the bucket is set to "standard" and downloads should be free. 

Could someone please clarify the current status? 

Thank you!

**Comment by zhangpicb** [comment]
Hi @davek44 

Thanks for the shared data.But the data is unaviable.

![Image](https://github.com/user-attachments/assets/b98439be-fd40-484d-95ee-18b5d572ea00)
