### ISSUE TITLE
Impact of custom hg38 with common alleles

### ISSUE THREAD

**Issue by ekinda** [calico/borzoi#32]
Hello, I am curious about the impact of using a custom reference genome with the most common alleles at each position edited in. As far as I could see, this is not mentioned in the original preprint.

1. Do you see an improvement in performance by using this approach?
2. How many positions are changed compared to hg38?
3. Did you try other approaches such as dynamically augmenting the data with the most common alleles, instead of a new reference?

Best
Ekin

**Comment by davek44** [comment]
The released model does not use a custom reference genome. We're still experimenting with this. We haven't tried dynamic augmentation.

**Comment by ekinda** [comment]
I asked this question because this page states that the modified version was used in the latest models: https://github.com/calico/borzoi/tree/main/tutorials/latest/make_data.

If you have any results in the future on the impact of common alleles I would be very interested to see them.

Thanks for the responses, and very impressive work!
