### ISSUE TITLE
The targets table missing 

### ISSUE THREAD

**Issue by louadi** [calico/borzoi#8]
Hi again,

I m trying to run the borzoi_sed_paqtl_cov.py  script but I need the "Targets_file", do you have any examples of this file or it is format? 

`python src/scripts/borzoi_sed_paqtl_cov.py   params_pred.json model0_best.h5 variants.vcf
Usage: borzoi_sed_paqtl_cov.py [options] <params_file> <model_file> <vcf_file>` 

borzoi_sed_paqtl_cov.py: error: Must provide targets table to properly handle strands`

```python 
    parser.add_option(
        "-t",
        dest="targets_file",
        default=None,
        type="str",
        help="File specifying target indexes and labels in table format",
    )
```

As I understand from the function below that the file need to have name and strand_pair columns, but any other requirement?

P.S: the column "name" is missing in the target file you provided. So I am assuming it is a different file?

```python 
def targets_prep_strand(targets_df):
    # attach strand
    targets_strand = []
    for _, target in targets_df.iterrows():
        if target.strand_pair == target.name:
            targets_strand.append(".")
        else:
            targets_strand.append(target.identifier[-1])
    targets_df["strand"] = targets_strand

    # collapse stranded
    strand_mask = targets_df.strand != "-"
    targets_strand_df = targets_df[strand_mask]

    return targets_strand_df
```

Thank you again for your support!

Best ,
Z.L

**Comment by louadi** [comment]
I think I understood the format of the Targets_file. Closing this.

**Comment by Al-Murphy** [comment]
Hey @louadi, I'm also unsure what to use for the `targets_file`, what did you go for in the end? Thought it might be [targets_human.txt](https://raw.githubusercontent.com/calico/borzoi/main/examples/targets_human.txt) but I'm not sure that's right?

**Comment by louadi** [comment]
Hey,

Yes indeed it is the [targets_human.txt](https://raw.githubusercontent.com/calico/borzoi/main/examples/targets_human.txt).

Best,
Zaka
